### ISSUE TITLE
Insufficient indentation of code generated by Enlighter 

### ISSUE THREAD

**Issue by fouquet** [Lighter-swift/Lighter#16]
I've got the issue that the `create` code generated by Enlighter does not properly indent the multi-line string literal and thus creates a compilation error:

`Insufficient indentation of next 4 lines in multi-line string literal`

Sample SQL:

```
CREATE TABLE IF NOT EXISTS "TestTable" (
  "id" integer PRIMARY KEY NOT NULL,
  "someText" text(128),
  "someInt" integer(128),
  "someFloat" real(128)
);
```

Code generated:

```
/// The SQL used to create the `TestTable` table.
    public static let create = 
      #"""
      CREATE TABLE "TestTable" (
  "id" INTEGER PRIMARY KEY NOT NULL,
  "someText" text(128),
  "someInt" integer(128),
  "someFloat" real(128)
);
      """#
```

Manually adding the generated code to the codebase and fixing the indentation compiles just fine.

Lighter: 1.0.16
Xcode 14.1

**Comment by helje5** [comment]
Hm, that seems to work fine for me:
```
    /// The SQL used to create the `TestTable` table.
    public static let create = 
      #"""
      CREATE TABLE "TestTable" (
        "id" integer PRIMARY KEY NOT NULL,
        "someText" text(128),
        "someInt" integer(128),
        "someFloat" real(128)
      );
      """#
```
Maybe that happens on copy/paste in Xcode?

**Comment by helje5** [comment]
Oh, is this the Swift Package Plugin or actually Enlighter the app?

**Comment by fouquet** [comment]
Oh sorry, forgot to mention - it's the plugin.

**Comment by helje5** [comment]
The strange thing is that it works for me 🤔 
<img width="761" alt="Screenshot 2022-11-29 at 14 52 13" src="https://user-images.githubusercontent.com/7712892/204546898-d009f8ec-ef04-4c30-8e5f-c59f95104543.png">

**Comment by fouquet** [comment]
I've recently updated to Ventura. And guess what, it works fine now. Could this actually be a bug that only shows up on Monterey?

**Comment by helje5** [comment]
Since I'm not on Ventura yet, that seems unlikely. Rather some option which doesn't transfer or sth

**Comment by helje5** [comment]
I guess we can close this then :-)
