### ISSUE TITLE
Xcode 14.3 (14E222b) not detecting build tool plugin

### ISSUE THREAD

**Issue by zachcoyle** [Lighter-swift/Lighter#21]
Not sure if this is an xcode bug or not, but I am unable to add the build tool after updating xcode.

<img width="356" alt="Screenshot 2023-04-02 at 11 28 18 AM" src="https://user-images.githubusercontent.com/908716/229362758-3980a51b-1a2f-4eba-bad2-1d36d757b926.png">

**Comment by helje5** [comment]
Sigh, I'll have a look.

**Comment by zachcoyle** [comment]
Very much appreciated. I know nothing about the build plugins so I wasn’t sure how to go about checking things out

**Comment by helje5** [comment]
Hm, interesting, that seems to be be more like a Package.swift resolution issue. Might be a simple fix, checking.

**Comment by helje5** [comment]
Should be fixed in 1.0.20, let me know if it doesn't work!

**Comment by zachcoyle** [comment]
Thanks man! I’ll try it out when I get back to my computer!

**Comment by zachcoyle** [comment]
Thank you this fixed it!
