### ISSUE TITLE
Enlighten generates ambigous symbols if `Table` shares name of `Database`

### ISSUE THREAD

**Issue by JoeMatt** [Lighter-swift/Lighter#32]
If a Database has a Table of the same name, ambiguous references are created.

Example database; https://github.com/SnowflakePowered/shiragame/releases/latest/download/shiragame.zip

To reproduce
1. Insert Shiragame.sqlite3 
2. Use swift pm plugin to generate
3. Build

Workaround;
Edit the database Table name to something unique e.g. `Shiragame_metadata`

**Comment by helje5** [comment]
Hm, yes, the easy fix is to just rename the DB to ShiragameDB.db (I think there is also a config option to specify the database type name). 
But yes, Enlighter should just check whether there is a table naming conflict w/ the DB, and add "Database" or "DB" automatically for the default name.
